import PageAccueil from '@/components/pageAccueil'
import Video from '@/components/pageAccueil/Video'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Alain Terrieur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon-16x16.png" />
      </Head>
      <main>
        <PageAccueil />
      </main>
    </>
  )
}
